version: "3.9"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./../Docker/backend/Dockerfile
    volumes:
      - ./backend:/backend
    tty: true
  test:
    build: 
      context: ./backend
      dockerfile: ./../Docker/test/Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - 4000:8080
    tty: true