micronaut:
  router:
    versioning:
      enabled: true
      parameter:
        enabled: false
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
    static-resources:
      swagger:
          paths: classpath:META-INF/swagger
          mapping: /swagger/**
      swagger-ui:
          paths: classpath:META-INF/swagger/views/swagger-ui
          mapping: /swagger-ui/**
      dokka:
        paths: classpath:META-INF/dokka
        mapping: /dokka/**
      test:
          paths: classpath:META-INF/test
          mapping: /test/**
      jacoco:
          paths: classpath:META-INF/jacoco
          mapping: /jacoco/**
      license:
          paths: classpath:META-INF/licenses
          mapping: /license/**
  application:
    name: backend
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_TABLE}
    driverClassName: org.postgresql.Driver
    db-type: postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
