micronaut:
  router:
    versioning:
      enabled: true
      parameter:
        enabled: false
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
  application:
    name: backend
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://postgres:5432/postgres
    driverClassName: org.postgresql.Driver
    db-type: postgres
    username: postgres
    password: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
